--- #YAML:1.0
name:               Authen-Credential
version:            1.0_1
abstract:           abstraction of a credential
author:
    - Lionel Cons <lionel.cons@cern.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Base64:      0
    No::Worries:       0
    Params::Validate:  0
    Test::More:        0
    URI::Escape:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
